services:
  postgres:
    image: postgres:15-alpine
    container_name: examhub_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: examhub_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./database/insert_admin.sql:/docker-entrypoint-initdb.d/2_insert_admin.sql

volumes:
  postgres_data: